### PR TITLE
Working and starting

### PR DESCRIPTION
**Pull request by KnKay**
Hi,

I had to make another change yesterday. The CFFI IBackend was not happy with the installed Python version. 
I fixed it and can confirm it workin on my machine. 

I also added the documentation work. 

Kind regards Kay!

### CODE REVIEW

**Comment by texadactyl** [comment]
@KnKay You might consider migrating from cffi to numba.  The advantage is that numba let's you code entirely in Python.

**Comment by texadactyl** [comment]
@KnKay Sorry but I have had little time lately for my hobbies.

**Comment by KnKay** [comment]
> 
> 
> @KnKay Sorry but I have had little time lately for my hobbies.

@texadactyl No problem! Same here. Almost forgot the open request!

**Comment by texadactyl** [comment]
@KnKay 

I've made some other changes:
* Preparation notes corrections
* Minor bug fixes
* Enhancement: copy any extensions in the user CSR to the user cert.

Off and on, I've thought about the docker approach.  If diyca was running as an ordinary user process, I would probably agree to make the changes.  However, diyca was designed to run as a root process, triggered by systemctl as a rc-local.service.  You could say that I took the easy way out - fair enough.  I have chosen to leave the diyca run model as-is.

I hope all is well with you.

Richard

**Comment by KnKay** [comment]
Hi Richard,

I am fine, thank you! 
Totally happy with your decision. Maybe it make sense to keep things like they are on such small devices like the Raspberry! 

Cheers!

**Pull request closed without merging**
